### ISSUE TITLE
Only use nuxt-svgo for certain folder

### ISSUE THREAD

**Issue by IlyaSemenov** [cpsoinos/nuxt-svgo#138]
Enabling `nuxt-svgo` in an existing project breaks all existing images that are included with `<img src="@/assets/logo.svg">`. This code starts to emit empty `<img>` tag.

I know I can work around that with `<img src="@/assets/logo.svg?url">` but that's not really a good DX. A project may have hundreds of images inserted with different means. A developer wouldn't expect that they have to update a huge amount of codebase just for the sake of adding a couple colorizable icons with nuxt-svgo.

Can we have an option to only enable svgo for a certain folder, such as `assets/icons`? That would allow to add `nuxt-svgo` to existing projects without breaking things.

**Comment by jd1378** [comment]
I understand, I agree, I'll look into it soon

**Comment by jd1378** [comment]
Sadly this is a little tricky, since [nuxt 3.4.3](https://github.com/nuxt/nuxt/discussions/20568#discussioncomment-5763466) broke the module, which [at first was appending a query to the import for auto imports](https://github.com/jd1378/nuxt-svgo-fork/blob/23670922b41178c264fed43c571012692f8dddaf/src/module.ts#L51-L55)
which would simplify doing this fix a lot easier if it didn't
without being able to do that on older versions (like yours which is specifically on 3.4.x), the fix gets tricky for components outside the auto import path

I'd like to know your opinion on this @IlyaSemenov

**Comment by IlyaSemenov** [comment]
Sure thing, if the module **does** depend on newer features, pin it to ^3.5 or ^3.6. My original point was that it shouldn't be pinned to  the latest edge, that's it.

**Comment by jd1378** [comment]
I wasn't talking about #140 
anyway, I did add a new option `explicitImportsOnly`, which will only process imports that explicitly use the query parameters supported by the vite plugin, and are outside the `autoImportPath` (files inside this path can omit the query)
since this is unstable (I don't know if it will work properly in all environments due to the poor path check), I won't document it on readme

I have laxed the dependencies as well, hopefully it doesn't break, the tests passed
If it did break, will release a fix soon after it, but tests passed, so I don't think there should be any problem

**Comment by jd1378** [comment]
@IlyaSemenov please try the new version and check if all of your issues are actually resolved :)

**Comment by IlyaSemenov** [comment]
@jd1378 works good, thanks! The `?url` is no more required for the legacy code base.

Question though, I was wondering if `<img src="@/assets/logo.svg">` could somehow benefit from `nuxt-svgo`? With `?url` (or with `{ explicitImportsOnly: true }` now) the files are delivered verbatim. Any idea how to process them with svgo?

**Comment by IlyaSemenov** [comment]
Oh, I see, this is discussed in #124.

**Comment by jd1378** [comment]
The thing is I could not figure out how to optimize the SVG file, but return a URL of the optimized file
it seems like vite.js does not support such a thing, Or I am not aware of how it's done
if you found out how it's done, please let me know and I'll take a look

**Comment by jd1378** [comment]
actually I think I figured it out
probably `transform` is what I was looking for

**Comment by jd1378** [comment]
No. I don't think it's possible
tracking what it does:
https://github.com/vitejs/vite/blob/8f109a67bd54b0eb7679fe1fafc56e03a247b768/packages/vite/src/node/plugins/asset.ts#L182
https://github.com/vitejs/vite/blob/8f109a67bd54b0eb7679fe1fafc56e03a247b768/packages/vite/src/node/plugins/asset.ts#L241
I'm afraid vite.js does not provide a way to do this yet.
