### ISSUE TITLE
Cannot Find Module 

### ISSUE THREAD

**Issue by Skylercrane23** [cpsoinos/nuxt-svgo#40]
when importing an icon like `import BarsSolid from '~~/assets/icons/bars-solid.svg'` I get a TS warning saying `Cannot find module '~~/assets/icons/bars-solid.svg' or its corresponding type declarations.ts(2307)`

Icons are working but typing must be missing?

**Comment by MRinaldi9** [comment]
@Skylercrane23 i'm having the same problem and i have resolved setting at the end of the import directory with the follow suffix: `?component`.
In the documentation there is the command for create, during local development, the types for the component but i don't think it is updated: `pnpm dev:prepare`

**Comment by Skylercrane23** [comment]
Awesome, yeah the `?component` fixed it for me. Thanks!

**Comment by cpsoinos** [comment]
Hey @Skylercrane23, in order to fix this TypeScript error you need to provide a type declaration to tell TypeScript how to handle SVG components. Here's an example:

```ts
// ./custom.d.ts

declare module '*.svg' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent
  export default component
}
```

<img width="627" alt="image" src="https://user-images.githubusercontent.com/10081464/187083569-a5ab0634-8378-4bda-af40-69221cca41b3.png">

I'll add this to the readme!
