### ISSUE TITLE
This SVGO version is no longer supported. Upgrade to v2.x.x.

### ISSUE THREAD

**Issue by dosstx** [cpsoinos/nuxt-svgo#70]
When running `npm run dev` in Nuxt 3, I get the following warning: `svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.`

What should be done, if anyting?

**Comment by cpsoinos** [comment]
That warning is due to a dependency in `vue-svg-loader`, which is part of the webpack loader that this module adds. Because of that warning, this module isn't using svgo from `vue-svg-loader`, and instead uses `svgo-loader`: https://github.com/cpsoinos/nuxt-svgo/blob/main/src/module.ts#L42-L51

You're welcome to open a PR to quiet or fix this warning!

**Comment by samuelhnrq** [comment]
Am using NPM and simply adding to package.json
```jsonc
{
   // ...
  "overrides": {
    "svgo": "^2"
  }
}
```
worked flawlessly without any noticiable hiccups, besides fixing the warning it also fixed the audit security vunerabilities, you might want to be more conservative on the version constraint of svgo to a specific version insead of such a wide range

**Comment by jd1378** [comment]
@cpsoinos maybe drop webpack support in favor of https://github.com/oliverfindl/vue-svg-inline-loader ?

**Comment by jd1378** [comment]
@cpsoinos I think we can close this ?

**Comment by jd1378** [comment]
I'm closing this since nuxt-svgo no longer depends on `vue-svg-loader` directly
